### ISSUE TITLE
[Juno beta1] Night Light doesn't work at all

### ISSUE THREAD

**Issue by arshubham** [elementary/switchboard-plug-display#103]
System: HP pavilion 15 ab series
Dual-Core Intel® Core™ i5-5200U CPU @ 2.20GHz
Intel Corporation HD Graphics 5500 (rev 09)
NVIDIA Corporation GM108M [GeForce 940M] (rev a2)

![image](https://user-images.githubusercontent.com/14235191/42241359-47033d8c-7ed8-11e8-9b5b-119f2debc448.png)

If i can provide any further debug information, please ask me. the -d flag doesn't seem to work now on switchboard

**Comment by cassidyjames** [comment]
@arshubham pardon the obvious, but was it between 20:00 and 06:00 when you observed this? Do you have a single display, or multiple?

**Comment by arshubham** [comment]
@cassidyjames Sorry for this. I get it now. I am in India (in the correct schedule) but my laptop timezone was wrong. But Ideally shouldn't there be a switch for turning off the schedule. An on/off switch for nightlight should just ignore the schedule. I will close it now.

**Comment by cassidyjames** [comment]
@arshubham no worries! Thank you for reporting issues. :smile:
