### ISSUE TITLE
Rotation lock shows for touch screens, not accelerometer

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-display#116]
Having a touch screen doesn't necessary imply that there is an accelerometer. We should be checking for that specific hardware, not assuming one implies another.

**Comment by coverme76** [comment]
this was reported on the belated [google plus comm](https://plus.google.com/111553066250432649921/posts/FeMvWe4bR2S).

**Comment by junk33e53** [comment]
same with me. login screen is rotated while the desktop is ok

**Comment by peteruithoven** [comment]
Workaround: https://elementaryos.stackexchange.com/questions/8924/how-to-disable-rotation
