### ISSUE TITLE
Schedule time defaults to 24h time even when AM/PM is selected

### ISSUE THREAD

**Issue by D0J0P** [elementary/switchboard-plug-display#122]
I have "AM/PM" selected in Time Format in the Date & Time settings, and the time format in the Night Light schedule still shows as 24h time
![screenshot from 2018-09-21 14 47 48](https://user-images.githubusercontent.com/19495660/45900336-7bdef000-bdad-11e8-89ff-2e25c00a2c5c.png)

**Comment by kgrubb** [comment]
I also can no longer confirm this issue.  Looks like it no longer happens in Hera.
