### ISSUE TITLE
Add 3× scaling setting

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-display#130]
Modern hardware is cropping up where 3× scaling might make sense. We should probably go ahead and add it to the scaling factor combobox.

**Comment by cassidyjames** [comment]
Trying to think of the right UI copy for this. Right now we have three options:
- Automatic
- LoDPI
- Pixel Doubled

"Pixel Tripled" sounds weird, and I think it'd make more sense to break into 3× at that point. Do we do something like this?

- Automatic
- LoDPI (1×)
- HiDPI (2×)
- HiDPI (3×)

Or is having the scaling factor listed there a little weird?

**Comment by jlnr** [comment]
Assuming that users will change this setting because things are too small/large on their screen, I think "Zoom: 100% / 200% / 300%" is easier to understand.

Since any change here requires a reboot, it would also be nice if "Automatic" was more specific ("Automatic (200%)") so that users don't change it from "Automatic" to e.g. 200%, only to discover that everything looks the same after a reboot.

**Comment by cassidyjames** [comment]
And I guess for completeness, here's the smallest diff, but I don't like it:

**Scaling factor:**
- Automatic
- LoDPI
- Pixel Doubled
- 3× Scaling (or something)

**Comment by SixFingeredAmish** [comment]
> * Automatic
> * LoDPI (1×)
> * HiDPI (2×)
> * HiDPI (3×)

This is a good solution @cassidyjames

**Comment by matej-marcisovsky** [comment]
What about this:

* Automatic
* LoDPI
* HiDPI
* HiDPI+

Scaling factor is weird and kinda useless for regular users. As a user you have to think about what the number in parenthesis is representing - scale, zoom, three times what?

**Comment by cassidyjames** [comment]
HiDPI+ isn't an industry standard term at all, though. I think in this case I'd like to be more honest/up-front about the scaling factor. We'd also label the dropdown as "Scaling factor" still.

**Comment by jlnr** [comment]
To add one more objection, LoDPI is not an industry standard term either, and I think it sounds a little condescending. There's nothing wrong with 1440p at 27", or 1080p/1200p at 24". I don't have a good suggestion for an alternative, though. (Percentages ftw 😬)

**Comment by tintou** [comment]
Scaling factor: `1×` `2×` … `n×`
Btw, we don't have to hardcode the max number anymore, we can just get that number from Mutter (this combobox predates Mutter support)

**Comment by cassidyjames** [comment]
@tintou I would like to distinguish between loDPI and HiDPI since those are terms we use when talking about elementary OS, and at the very least if someone doesn't understand scaling factors, that's another possibly-familiar term they could recognize.

**Comment by matej-marcisovsky** [comment]
What about scaling factor as number input/slider with a hint text? If user slides the scale factor to 2x hint text shows up telling him that this is a good value for HiDPI monitors etc.

**Comment by cassidyjames** [comment]
Fixed in the simplest case by #262
