### ISSUE TITLE
Wrong link in System Settings > About > Report a Problem

### ISSUE THREAD

**Issue by wout** [elementary/switchboard-plug-display#137]
The linked repo for this section in **System Settings > About > Report a Problem** is https://github.com/elementary/switchboard-plug-displays/issues, resulting in a 404.

**Comment by ryonakano** [comment]
It was fixed in https://github.com/elementary/switchboard-plug-about/commit/98063a66ea2e7ef20cee7a3a0b3b008e025c92af and that fix will be applied to the system when a new version of switchboard-plug-about is released
