### ISSUE TITLE
Many HiDPI issues

### ISSUE THREAD

**Issue by wout** [elementary/switchboard-plug-display#140]
Yesterday my first 4k monitor arrived and I was very excited. Unfortunately, I discovered a series of issues with HiDPI mode in elementary OS. I need to mention my laptop (Dell XPS 9560) has a FHD display, but it is turned off. I only switch between HiDPI and LoDPI when I disconnect the external monitor.

**Cursor size**
I had to restart a lot to test things and more than often I got a cursor at the wrong size. In LoDPI a double sized cursor and the other way around. I could not read a pattern after restarting many times. So getting the cursor at the right size was just a matter of luck.

**Multitasking view docks size**
Randomly, after a reboot, the slots for application icons were half the required size in HiDPI mode. So application icons didn't fit into it. Stranger was the Thunderbird icon, floating outside of the gird, even after various reboots. I couldn't even drag Thunderbird to another workspace. I need to mention I am using the latest release downloaded from Mozilla, so Thunderbird is added using the AppEditor app with the svg icon applied manually.

**Flipping out of HiDPI mode mid-session**
This happened a few times. Suddenly, for no particular reason, HiDPI was disabled mid-session. The only solution was to reboot.

**Icons/UI in some prominent apps dont's scale along**
Probably not elementary OS related, but icons in GIMP and Inkscape don't scale along. Granted, the icons can be set to a larger size manually (Houdini even has an HiDPI UI mode which requires restarting the app) but in a mixed environment with LoDPI and HiDPI that's a lot of UI switching for the apps that don't get deal with it automatically. For me reason enough to pull the plug in the HiDPI story. Maybe I'll try again next year.

**Comment by peteruithoven** [comment]
Please break this up into specific issues into individual issues. 

For the Multitasking view docks size issue i'd love to see screenshots. 

> Probably not elementary OS related, but icons in GIMP and Inkscape don't scale along. Granted, the icons can be set to a larger size manually
In what context?

**Comment by wout** [comment]
> In what context?

I'm not sure what you mean, but GIMP and Inkscape maintain the LoDPI UI while in HiDPI mode. os the icons are tiny and can only be scaled up manually in the app's settings/preferences panel.

**Comment by peteruithoven** [comment]
Ah Sorry, I was thinking about icons of those apps in elementary. I'm afraid there is not a lot elementary OS can do there. I'm no expert but this is indeed probably application specific. Gimp 2.10.6 that I've installed as snap seems to handle HiDPI better.

**Comment by peteruithoven** [comment]
Ah interesting. I'm assuming this dpi switching is why you're running into more HiDPI issues. I for example haven't seen these issues. (Dell XPS 9550 with 4k screen). 

Inkscape 0.92.3
![screenshot from 2018-10-26 13 37 16](https://user-images.githubusercontent.com/523210/47564366-096dac80-d925-11e8-8b4f-29623e1d06f8.png)
Gimp 2.10.6
![screenshot from 2018-10-26 13 37 09](https://user-images.githubusercontent.com/523210/47564367-0a064300-d925-11e8-8b18-6c2b71a9cb60.png)

**Comment by wout** [comment]
Great, thanks! That's good to know. So my next laptop will have a built-in 4k monitor, too.
