### ISSUE TITLE
Flipping out of HiDPI mode mid-session

### ISSUE THREAD

**Issue by wout** [elementary/switchboard-plug-display#143]
This happened a few times. Suddenly, for no particular reason, HiDPI was disabled mid-session. The only solution was to reboot.

**Comment by peteruithoven** [comment]
I'm afraid this is out of the scope of the Display settings and is a more general issue. Could you move this to https://github.com/elementary/os/ ?
For some reason Github doesn't have the functionality to make this easy, but you could use: https://github-issue-mover.appspot.com/

**Comment by wout** [comment]
Sure, although just creating a new issue seems to be just as easy. :)
