### ISSUE TITLE
GL 4FPS BLIT-VSYNC ON

### ISSUE THREAD

**Issue by dackdel** [elementary/switchboard-plug-display#148]
![screenshot from 2018-11-23 15-22-24](https://user-images.githubusercontent.com/380951/48937677-e854a780-ef34-11e8-867a-4f8533429829.png)
This shows up on the top left of every single application. How do I get rid of it? I am running juno with Quad-Core Intel® Core™ i7-7700HQ CPU @ 2.80GHz, Intel Corporation Device 591b (rev 04), NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] (rev a1) and the nvidia 410.73 driver installed.

**Comment by peteruithoven** [comment]
Thanks for reporting. This is the first time I've seen this, it's highly unlikely the display settings enabled it. 
Did you perhaps enabled something in the Nvidia settings application?

**Comment by dackdel** [comment]
any suggestions as to what i should be looking for, yes i did try to find a setting that kept it on high performance mode instead of adaptive so i did fiddle around. not sure what to change. 
![screenshot from 2018-11-23 15-39-16](https://user-images.githubusercontent.com/380951/48938027-feaf3300-ef35-11e8-8546-265f2afd2517.png)

**Comment by dackdel** [comment]
closed by mistake.

**Comment by arshubham** [comment]
Try disabling `Enable Graphics API visual Indicator' checkbox under `OPENGL SETTINGS`

**Comment by dackdel** [comment]
aaaaaaaand i feel like a noob. thank you.

**Comment by tiagofrancafernandes** [comment]
> aaaaaaaand i feel like a noob. thank you.

me too kkk
