### ISSUE TITLE
not only allow whole hours in the user-defined settings

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/switchboard-plug-display#155]
what it says on the thin.
At the moment it is possible to enter half and quarter hours (or values like 18:03) in a 24 hour time system, but as soon as I close Switchboard, the setting is reset to the last output value.

**Comment by 4jNsY6fCVqZv** [comment]
Thanks Cody for moving!
Peter, do you think that the setting also works correct with 18:03, for example, but is just not shown in the plugin?

**Comment by 4jNsY6fCVqZv** [comment]
@peteruithoven The issue is still relevant. Any idea how to solve this elegantly?

**Comment by ryonakano** [comment]
@4jNsY6fCVqZv I've submitted a PR (#173) that should fix this issue.

**Comment by 4jNsY6fCVqZv** [comment]
@ryonakano Thank you very much, hope it works as intended and can be merged!
