### ISSUE TITLE
Change the display color from blue to something easy on the eyes.

### ISSUE THREAD

**Issue by uncertainquark** [elementary/switchboard-plug-display#156]
Change the display color from blue to something easy on the eyes. Too much blue is unpleasant to look at.

![screenshot from 2019-02-27 07-18-19](https://user-images.githubusercontent.com/22585732/53479951-316e4780-3aa0-11e9-8841-968bba108f79.png)

**Comment by peteruithoven** [comment]
Please note that this is just the first color from a palette that's used to differentiate between displays. 
Currently: https://github.com/elementary/switchboard-plug-display/blob/18a2c876a9922ebc51dd89c4fc97d0e0a83dd262/src/Widgets/DisplaysOverlay.vala#L36

We should probably switch to using the constants (like `@STRAWBERRY_300`), like: https://github.com/elementary/calendar/pull/293/files

And maybe we can use the softer 100 variants?
https://elementary.io/docs/human-interface-guidelines#color
https://github.com/elementary/stylesheet/blob/master/elementary/gtk-3.0/palette.css

Or maybe we can use a more neutral fill color and use a border to differentiate?
