### ISSUE TITLE
[Multimonitor]

### ISSUE THREAD

**Issue by bbetter** [elementary/switchboard-plug-display#165]
Chrome: Full screen videos fails to be opened on non-primary monitor. Video just lags and stays on same frame while keep on switching on and off full-screen. Can only be fixed by closing browser itself.
It only reproduces in elementary OS , but I'm not sure it's the right place to report it in this plugin repo.

**Comment by peteruithoven** [comment]
Thanks for reporting. This is most likely an issue for [Gala](https://github.com/elementary/gala), the window manager. What your describing sounds like what's reported in: https://github.com/elementary/gala/issues/404
