### ISSUE TITLE
[Feature Request] Gradual change in warmth of screen color.

### ISSUE THREAD

**Issue by JuanSpecht** [elementary/switchboard-plug-display#172]
It doesn't feel pleasant to the eye during the first minutes when Night Light starts. So I thought it would be nice if the warmth of the screen could increase imperceptibly throughout he day, using the location to calculate sun hours.
Apps like Redshift and F.lux already have that functionality, but it would be nice to have it integrated in Night Light.
How technically difficult would it be to implement something this?

Mockup for reference:
![mockup](https://user-images.githubusercontent.com/52331039/61566554-fb336380-aa52-11e9-86b7-31314119aa45.png)

**Comment by peteruithoven** [comment]
Under the hood elementary OS uses the [Gnome setting deamon](https://gitlab.gnome.org/GNOME/gnome-settings-daemon)'s Color plugin. We merely enable easy configuration with our own System Settings page and indicator. 

So please check[ their issue queue](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/issues/). 
This looks like a relevant one: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/issues/89

**Comment by peteruithoven** [comment]
It has been asked before in the indicator repo: https://github.com/elementary/wingpanel-indicator-nightlight/issues/36

**Comment by JuanSpecht** [comment]
Oh sorry, I should have looked better.
Thanks for your time!
