### ISSUE TITLE
Night Light time schedule is 1 hour off

### ISSUE THREAD

**Issue by Bruce-McL** [elementary/switchboard-plug-display#174]
System Settings: Displays: Night Light: Schedule: Manual.

I enter my time settings, and Night Light turns on one hour earlier. If I had to guess I'd say this is daylight savings related, and that after Daylight Savings goes off the time settings will be accurate.

**Comment by ryonakano** [comment]
@Bruce-McL Are you using the version of Switchboard Plug Display come with elementary OS Juno by default, or did you build and install the latest `master` branch?

**Comment by cassidyjames** [comment]
Also, I believe Night Light _begins_ to come on one hour early, so that it is fully transitioned in time for the schedule. The indicator appears then so you can toggle it back off if you'd like to.

**Comment by Bruce-McL** [comment]
> @Bruce-McL Are you using the version of Switchboard Plug Display come with elementary OS Juno by default, or did you build and install the latest `master` branch?

I am using what came with elementary OS Juno, no custom built parts.

> Also, I believe Night Light _begins_ to come on one hour early, so that it is fully transitioned in time for the schedule. The indicator appears then so you can toggle it back off if you'd like to.

That is quite a long transition time! On macOS and iOS I have the time set manually, and the transition time is about two minutes. I'm OK with the way I have elementary OS set up now. I guess I could play around with the settings in elementary OS to learn more about the transition time.

**Comment by cassidyjames** [comment]
@Bruce-McL the actual Night Light functionality is provided by [GNOME Settings Daemon](https://gitlab.gnome.org/GNOME/gnome-settings-daemon). A shorter (or configurable) transition time would need to be implemented there.
