### ISSUE TITLE
Be smarter about resolutions shown

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-display#178]
Right now, we show every. single. resolution. reported as supported by the display

![Screenshot from 2019-08-23 14 56 43@2x](https://user-images.githubusercontent.com/611168/63591080-66bea280-c5b6-11e9-9416-ed6bd98e8611.png)

This is whack. Instead, we should filter these by default with a way to expose all supported resolutions. At the very least, we should hide or deprioritize too-low resolutions that aren't supported by elementary OS in the first place. On HiDPI, we could also make sure the native resolution and the pixel-halved resolution (if supported) is shown—i.e. 3840×2160 and 1920×1080.

**Comment by jeremypw** [comment]
What is the minimum width and height supported by elementary?

**Comment by danrabbit** [comment]
@jeremypw yes, that's correct

**Comment by cassidyjames** [comment]
I haven't thought through the design super far, but in my mind, we would _just_ show:

- Native/highest resolution (not sure how that's communicated, but basically: the default resolution the display will use)
- If the display is HiDPI, then show the LoDPI equivalent (half in each dimension) if it's a supported resolution
- Maybe show all resolutions at or above the supported resolution in each dimension that also match the native aspect ratio (which I guess would include the previous bullet)

And then perhaps we have a way to "show all resolutions" that would give the massive, unfiltered list for weird edge cases we can't really predict.

So by default on my HiDPI display, that above list would become either:

- 3840×2160 (default)
- 1920×1080

or at most:

- 3840×2160
- 2880×1620
- 2048×1152
- 1920×1080
- 1600×900
- 1440×810
- 1368×768
- 1360×768

and then somehow/somewhere we could have a way to expand that to the whole list.

**Comment by jeremypw** [comment]
Yes, presumably the native resolution/aspect of the screen would normally be chosen unless running in a VM - any legibility issues can be dealt with by choosing a suitable text size.  On the other hand, the user has chosen to adjust the resolution if they have opened this list so I am not sure there is much benefit adding a second step to access all the available resolutions.  Maybe we could limit the height of the box and put "unlikely" resolutions at the bottom of the list.

**Comment by cassidyjames** [comment]
@jeremypw I do think we can provide more sensible default choices here by putting unlikely/potentially-problematic resolutions a step further away. That could mean below a separator in a list, or it could mean behind another click—I'm not too picky there. But I would greatly prefer a smaller, understandable, and "safe" list be the primary thing presented to avoid overwhelming users.
