### ISSUE TITLE
Deactivation of my secondary screen is ignored

### ISSUE THREAD

**Issue by grmain** [elementary/switchboard-plug-display#202]
Hi,
I got a computer screen (DVI) and a television (HDMI) connected to my graphic card. My TV is turned off most of the time, and as Pantheon Mail keeps launching on it, I wanted to deactivate it though the settings panel. But that setting keeps being ignored. Not after a startup, but, well, all the time. When I come back to Display settings, it is activated again.

**Comment by jeremypw** [comment]
Duplicate of #131
