### ISSUE TITLE
Please make an option to turn off screen rotation

### ISSUE THREAD

**Issue by bulbul0111** [elementary/switchboard-plug-display#230]
My pc is HP-ProBook-430-G5, I have very annoying screen rotation while I am changing laptop position. Make a rotation lock button please in screen settings.
It an laptop, not tablet or smartphone, this button is very usefull.
If you will make this, your build will be just great!!!

Thank you very much!

**Comment by cassidyjames** [comment]
Thanks for reporting this. It looks like it's a duplicate of #116.
