### ISSUE TITLE
Night Light does not work

### ISSUE THREAD

**Issue by muonsei** [elementary/switchboard-plug-display#235]
I want to make my display have a warmer color, but Night Light does not work. I tried turning it on and off, also tried to set to Manual from "Sunset to Sunrise" but nothing works. Even moving the temperature slider does not do anything.

Here are some information you might need:
**Elementary OS 5.1.3 Hera**

I have two graphics cards:
- Intel UHD Graphics 620
- NVIDIA GeForce MX150

**Comment by danirabbit** [comment]
Closing since this is probably driver related and We've updated the kernel since 5.x

see also #275
