### ISSUE TITLE
Display Settings not appear

### ISSUE THREAD

**Issue by fabioformiga** [elementary/switchboard-plug-display#245]
the display settings no longer appear on dell e7240.
![imagem](https://user-images.githubusercontent.com/60191810/82946635-9c097e00-9f96-11ea-9e98-e6ab833d5e8d.png)

**Comment by fabioformiga** [comment]
Solution change the theme

**Comment by davidmhewitt** [comment]
Indeed, these are the sorts of issues you can expect to see when you change the stylesheet. If the stylesheet does not provide the necessary classes to support elementary properly, things will break.

Closing as this is not an issue with the display plug.
