### ISSUE TITLE
Mark resolution combo as insensitive if only one resolution

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-display#252]
Like we do for refresh rates. PINEBOOK Pro, for example, only has 1920×1080 as a supported resolution.

**Comment by pongloongyeat** [comment]
Don't have the necessary H/W to test so I won't make a PR but I'm guessing this will suffice

https://github.com/pongloongyeat/switchboard-plug-display/blob/dbdc2e40eacf68f22c6af55a7faa0a391d3e6c8d/src/Widgets/DisplayWidget.vala#L163

**Comment by cassidyjames** [comment]
@pongloongyeat that link no longer resolves; do you recall what it linked to?
