### ISSUE TITLE
Screen will not dim

### ISSUE THREAD

**Issue by noahrobert03** [elementary/switchboard-plug-display#275]
Hello, my screen on elementary OS 5.1.7 Hera will not dim using the slider control, the night light also will not work. I had this problem using Ubuntu also but updated the kernel and it began working. Since I think that it will probability be fixed in the next kernel update I am making this comment just for FYI purposes.
Here is a screenshot of my OS version:
![image](https://user-images.githubusercontent.com/72221158/101091962-83e66d00-357e-11eb-9882-159636c91f3d.png)

**Comment by danirabbit** [comment]
Closing since OP said this was kernel related and we've definitely updated the Kernel since 2020 :)
