### ISSUE TITLE
use mirror

### ISSUE THREAD

**Issue by Vaibhav22p-qw** [elementary/switchboard-plug-display#277]

**Comment by meisenzahl** [comment]
@Vaibhav22p-qw could you please add a description of your issue.

Please provide:

- What happended
- Expected Behavior
- Steps to Reproduce

Use the template for **Bug Report** when creating a new issue for reference.

**Comment by danrabbit** [comment]
Since OP hasn't responded for over a week, closing as incomplete. Please feel free to reopen this issue with more information
