### ISSUE TITLE
Is it a bug about night-light mode ?

### ISSUE THREAD

**Issue by wyn-p** [elementary/switchboard-plug-display#279]
When "night light" turn on, monitor display is brighter(blue) than turn off.
![P_20201219_201319](https://user-images.githubusercontent.com/76251195/102689294-e8b8ed00-4237-11eb-94ec-52cda26bb658.jpg)
![P_20201219_201323](https://user-images.githubusercontent.com/76251195/102689295-e9ea1a00-4237-11eb-9655-d2b3f3a58aec.jpg)

I'm so excited about elementary os version 6 and I considered eOS is the best linux distribution I've been used. So FIGHTING!!

**Comment by pongloongyeat** [comment]
Turning on the switch means to snooze night light, meaning night light is turned off so your monitor should be bluer (~6500K should be the default I assume). This isn't an issue.

**Comment by danirabbit** [comment]
Yup closing since this switch is for snoozing
