### ISSUE TITLE
display settings blank

### ISSUE THREAD

**Issue by lortkazuma** [elementary/switchboard-plug-display#288]
Hi!, I am got some problem at the preview display setting. it's blank, i can't setup for multi screen, preview like this  
![Screenshot from 2021-03-02 09-10-24](https://user-images.githubusercontent.com/75782974/109587107-158f5780-7b39-11eb-94c6-47ecd622420f.png)

**Comment by ryonakano** [comment]
Don't you see anything even if you use the default elementary theme?

**Comment by lortkazuma** [comment]
I just did, and it worked, thanks for the help

**Comment by lortkazuma** [comment]
I see the setting after change the theme to the default

**Comment by ryonakano** [comment]
Then I guess this is because of the custom theme you're using; it does not seem to support the widgets used here. So you may want to request its developer to add that support. Closing as out-of-scope since this issue is not due to the elementary OS itself.

**Comment by lortkazuma** [comment]
OK dude thanks helping
