### ISSUE TITLE
Unable to disable laptop display when connected to external monitor

### ISSUE THREAD

**Issue by louis993546** [elementary/switchboard-plug-display#297]
## What Happened
Even though "Use this display" is off, the laptop display is still being used. 

![Screenshot from 2021-06-12 16-24-40@2x](https://user-images.githubusercontent.com/3873011/121779304-400e9900-cb9b-11eb-85de-f36f68658b34.png)

## Expected Behavior
When "Use this display" is off, that display should actually be off

## Steps to Reproduce

1. Connect to external display
2. Try to turn the laptop monitor off, using the "Use this monitor" toggle

### Logs

Not sure what is the name of this app to do retrieve debug in the doc. 

## Platform Information

- elementary OS 6 Early Access
- Lenovo ThinkPad T480
    - i7-8550U
    - 20GB RAM
    - NVIDIA MX150 (But i am not sure how to check if it's being used)
- LG 32UK550-B (which is a 32" monitor, not a 27" one as stated in the screenshot. But that's really minor)

**Comment by jeremypw** [comment]
Looks like a duplicate of https://github.com/elementary/switchboard-plug-display/issues/274 and #134.  There is a draft PR here #228 aimed at fixing this but it needs some attention.

**Comment by louis993546** [comment]
Got it. Thanks!
