### ISSUE TITLE
Enable this display switch is not working on certain layouts

### ISSUE THREAD

**Issue by Hedronmx** [elementary/switchboard-plug-display#314]
I am currently using the layout of the image, it mimics real life position. I am trying to disable the top monitor, it works when I put them side by side

getting this error `** (io.elementary.switchboard:7219): CRITICAL **: 15:30:33.253: MonitorManager.vala:241: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Logical monitors positions are offset`

![Screenshot from 2021-08-18 15-31-01](https://user-images.githubusercontent.com/26935602/130018913-949d5154-1e5f-41db-8abf-85eaf3480c80.png)

_Originally posted by @davidmhewitt in https://github.com/elementary/switchboard-plug-display/issues/311#issuecomment-901636334_

**Comment by davidmhewitt** [comment]
I think I understand what's going on. Can you test the following?

Put the monitor you want to disable at the right of the other 3 and try to disable it (I think it should work)

Put it below the 3, I think this should also work.

However, on the left or above, it probably won't?

**Comment by Hedronmx** [comment]
@davidmhewitt You are absolutely correct, right and down work. Left and up does not

**Comment by davidmhewitt** [comment]
Thanks, I understand what's causing that, hopefully I'll find time to push a fix in the next week or so.

**Comment by Hedronmx** [comment]
Awesome! Thanks

**Comment by davidmhewitt** [comment]
@Hedronmx I've opened #315 

If you're able and willing, it would be good if you could test that branch and see if it resolves the issue for you. I have less monitors than you to test with :sweat_smile:
