### ISSUE TITLE
Windows sizing on multiple monitor setup (4k & 1080p  combo)

### ISSUE THREAD

**Issue by aberba** [elementary/switchboard-plug-display#317]
I have a Thinkpad with a 1080p display, and an external 4k monitor plugged in (external monitor being primary display). When  I open an app on the 4k external display and drag the app's window onto the 1080p, the size just overflows and I'm unable to resize the window on the 1080p laptop when I loose control of the cursor whilst dragging due it overflowing the screen size). 

This also happens when the app is opened on the 1080p secondary display, the app windows is sized based on the external 4k primary display and I'm unable to resize the window. 

The only way I've found around this is to use the multitask overview to drag onto the bigger display and resize there.

**Comment by lenemter** [comment]
Closing in favour of https://github.com/elementary/switchboard-plug-display/issues/317
