### ISSUE TITLE
Display tag doesn't show on all workspaces

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-display#320]
## What Happened

The tag with the display name appears to only show on the desktop on which it was spawned. Possible regression from https://github.com/elementary/switchboard-plug-display/pull/318 ?

## Expected Behavior

Even if you switch workspaces the tag should always show

## Steps to Reproduce

1. Open display settings
2. Switch workspaces
3. Don't see the tag anymore

**Comment by cassidyjames** [comment]
I believe I noticed this in master before #318. But I think it should be as simple as calling [`Window.stick ()`](https://valadoc.org/gtk+-3.0/Gtk.Window.stick.html).
