### ISSUE TITLE
Nightlight only affects one monitor

### ISSUE THREAD

**Issue by momen** [elementary/switchboard-plug-display#335]
Turning on nightlight only affects one monitor in a dual-monitor setup

OS: elementary OS 5.1
Resolution: 1920x1080, 1920x1080
GPU:  GTX 1080 Ti

**Comment by peteruithoven** [comment]
I have no issue on my dual-monitor setup.

OS: elementary OS 6.1 Jólnir (Built on Ubuntu 20.04.5 LTS)
Resolution: 3000x2000, 3840x2160
GPU: Intel® Xe Graphics (TGL GT2)

5.1 (released on the 10 August 2021) is pretty old. Especially with the upcoming 7.0 release. Maybe consider updating?

**Comment by momen** [comment]
the same problem in elementary OS 6.1

**Comment by peteruithoven** [comment]
There was an existing issue with almost exactly the same name: https://github.com/elementary/switchboard-plug-display/issues/304
Please move your details there.
