### ISSUE TITLE
Resolution reported incorrectly

### ISSUE THREAD

**Issue by guythomson** [elementary/switchboard-plug-display#338]
### What Happened?

[I think the LG UltraGear 32GP850-B has a quirk in its EDID - it reports its max supported resolution as 3840 * 2160 resolution despite it actually being a 2560 * 1440 panel]

On other OSes, they normally come up in 4k with this monitor doing a shoddy job of downscaling. Elementary OS 7 seems to get it right, coming up in 2560 * 1440, however the Display Settings screen reports it as 3840 * 2160 at 60Hz.

If I switch to the 2k resolution, nothing happens to the screen but I get the is it ok prompt. Then I can switch to 4k at 60 Hz properly this time, the screen goes black and comes back in all its tiny downscaled glory. Once I'm there, I can successfully switch back to 2560 * 1440 at 144Hz (screen shot of settings attached). 

![Screenshot from 2023-02-01 16 47 40](https://user-images.githubusercontent.com/99534283/216112954-623bc3db-5c0c-4e7c-9e0b-065f57bd1c8c.png)

However, when I close and reopen display settings, the screen is showing that my monitor is running at 3840 * 2160 at 60Hz again.

![Screenshot from 2023-02-01 16 48 41](https://user-images.githubusercontent.com/99534283/216113090-209252ff-0664-4a84-b6df-9756380ff3d3.png)

### Steps to Reproduce

Open display settings

### Expected Behavior

The resolution and refresh rate should be correct

### OS Version

Elementary OS 7.0 (Horus)

### Software Version

Latest release with all current updates

### Log Output

No response

### Hardware Info:
Monitor: LG UltraGear 32GP850-B
CPU: i5-10210U
iGPU: UHD 620

**Comment by vjr** [comment]
@guythomson Are you able to try this potential fix here? https://github.com/elementary/switchboard-plug-display/pull/337

**Comment by guythomson** [comment]
I've checked it out and installed it - it's better but it doesn't fix the underlying problem.

- It does fix the issue with the resolution being wrong on first open though, now it displays 2560 * 1440 at 144 Hz when I first open it.
- However if I change to 3840 * 2160 at 60 Hz, close the settings screen, then reopen it, it goes back to displaying 2560 * 1440 at 144 Hz even though it clearly (or blurrily in this monitor's case!) isn't (screen shot attached)

![Screenshot from 2023-02-01 16 47 40](https://user-images.githubusercontent.com/99534283/216347418-c50ec3b8-bba9-4713-a2d3-f42a09f1a4c7.png)

**Comment by vjr** [comment]
OK let me see if I can update the PR over the weekend to better handle resolution changes.

**Comment by guythomson** [comment]
> OK let me see if I can update the PR over the weekend to better handle resolution changes.

Thanks!

**Comment by vjr** [comment]
@guythomson could you try the latest code from https://github.com/elementary/switchboard-plug-display/pull/337 and let us know how it works for you now?

I have a 4k TV which reports an additional larger resolution 4096x2160 and I *believe* I have been able to reproduce the issues you described and my latest commit (which works better for me) should improve things for you too.

**Comment by guythomson** [comment]
That's perfect - using current head of origin/prefer-native-aspect worked like a charm. Great job, thank you!

**Comment by vjr** [comment]
Thanks @guythomson for re testing and reporting back, appreciated.
