### ISSUE TITLE
Make it work with latest Gala [$110]

### ISSUE THREAD

**Issue by tintou** [elementary/switchboard-plug-display#70]
Get rid of libgnome-desktop-3.0, use libmutter DBus API

---
There is a bounty on this issue in [Bountysource](https://www.bountysource.com/issues/52640475-make-it-work-with-latest-gala)

**Comment by tintou** [comment]
started here
https://github.com/elementary/switchboard-plug-display/tree/tintou/mutter-api
help always welcome

**Comment by danrabbit** [comment]
Closing since the branch was merged. We can make new individual reports if there are regressions
