### ISSUE TITLE
optimize color like "splendid or bravia engine"

### ISSUE THREAD

**Issue by torikulhabib** [elementary/switchboard-plug-display#87]
elementary os will be the best
![asus-splendid-technology_425](https://user-images.githubusercontent.com/26135527/38159926-c0cc35f0-34dd-11e8-8334-b1190076b6e1.jpg)
![xperia bravia engine on off](https://user-images.githubusercontent.com/26135527/38159927-c4ff9d1a-34dd-11e8-99cc-8592adb342e5.png)

**Comment by cassidyjames** [comment]
This likely has overlap with #5
