### ISSUE TITLE
Dual-cable screen is shown as two separate screens

### ISSUE THREAD

**Issue by jlnr** [elementary/switchboard-plug-display#88]
I use the Dell UP2715K at 5K resolution via dual DisplayPort cables, where each cable transports one half of the pixels. It works just fine with the proprietary Nvidia drivers, and GNOME Settings correctly shows it as a single screen (screenshot from pop!_OS Nvidia live session):

![gnome-settings 2x](https://user-images.githubusercontent.com/70772/38294227-7151c066-37ea-11e8-9353-9185189218f4.png)

However, Switchboard shows both halves individually and even lets me lay them out (screenshot from the same session with the elementary-daily PPA):

![switchboard-displays 2x](https://user-images.githubusercontent.com/70772/38294228-7191f3d4-37ea-11e8-86cd-633b0ca655e2.png)

The layout changes don't even work, the screen is always one contiguous rectangle (thankfully).

Expected behavior: It appears as a single screen at 5K resolution.

(Did I mention that elementary looks glorious at 5K? :heart_eyes:)

**Comment by tintou** [comment]
This is currently being adapted the Mutter API so let us know if that's still broken once it's done

**Comment by jlnr** [comment]
This has indeed been fixed by the Mutter API work. :+1:
